/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "Platform_Types.h"
#include <stdio.h>

#define RCC_Base 0x40021000
#define PORTA_Base 0x40010800
#define APB2ENR *((volatile uint32*)(RCC_Base+0x18))
#define CRH_Register *((volatile uint32*)(PORTA_Base+0x04))
#define GPIOA_ODR_Reg *((volatile uint32*)(PORTA_Base+0x0C))
uint8 g_var[7]={1,2,3,4,5,6,7};
uint8 bss_var[3];



int main(void)
{
	APB2ENR |= (1<<2);
	CRH_Register &= 0xFF0FFFFF;
	CRH_Register |= 0X00200000;
	while(1)
	{
		GPIOA_ODR_Reg |= (1<<13);
		for(int i=0;i<100000;i++);
		GPIOA_ODR_Reg &= ~(1<<13);
		for(int i=0;i<100000;i++);
	}
}
